In [2]:
import numpy as np

### LT1 (October 2024)

In [12]:
#1a

X = np.array([[1, 0], [1, 1], [1, -1], [1, 2]])
y = np.array([[1], [2], [2], [3]])

In [22]:
w = np.linalg.inv(X.T@X) @ X.T @ y

In [36]:
np.shape(X.T@X)

(2, 2)

In [24]:
w

array([[1.8],
       [0.4]])

In [26]:
loss = (1/8)* (X @ w - y).T @ (X @ w - y)

In [28]:
loss

array([[0.15]])

In [44]:
#1b

w_ridge = np.linalg.inv((X.T @ X + 3*np.identity(2))) @ X.T @ y

In [46]:
w_ridge

array([[1.01694915],
       [0.44067797]])

In [48]:
#1d

kernel = np.array([[1, 0, 0], [1, 1, 1], [1, 1, 1], [1, 2, 4]])

In [52]:
w_k = np.linalg.inv(kernel.T @ kernel) @ kernel.T @ y

In [56]:
w_k.round(4)

array([[1.],
       [1.],
       [0.]])

In [60]:
loss_k = (1/8) * (kernel @ w_k - y).T @ (kernel @ w_k - y)

In [62]:
loss_k.round(4)

array([[0.]])

### LT1 (March 2024)

In [71]:
#1a

X = np.array([[1, 0], [1, 1], [1, -1], [1, 2]])
y = np.array([[1], [-1], [4], [-13]])

In [73]:
w = np.linalg.inv(X.T@X) @ X.T @ y

In [75]:
w

array([[ 0.4],
       [-5.3]])

In [77]:
loss = (1/8)* (X @ w - y).T @ (X @ w - y)

In [79]:
loss

array([[3.2875]])

In [89]:
#1b

loss_ridge = (1/8)* (X @ w - y).T @ (X @ w - y) + 1.2*(w.T @ w)

In [91]:
loss_ridge

array([[37.1875]])

In [93]:
kernel = np.array([[1, 0, 0, 0], [1, 1, 1, 1], [1, 1, -1, 1], [1, 2, 4, 8]])

In [95]:
kernel

array([[ 1,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 1,  1, -1,  1],
       [ 1,  2,  4,  8]])

In [97]:
w_kernel = np.linalg.inv(kernel.T @ kernel) @ kernel.T @ y

In [101]:
w_kernel.round(4)

array([[ 1.    ],
       [ 1.3333],
       [-2.5   ],
       [-0.8333]])